### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by trajection** [trajection/aimlapi-rs#1]
- Text models
  - [x] Completions
  - [ ] Function calling
  - [ ] Assistants & Threads
  - [ ] Embeddings
- Image models
  - [ ] Image generation
- Vision models
  - [ ] Image analysis
- Audio models
  - [ ] Audio generation (default & custom)
  - [ ] Audio extend
  - [ ] Fetch generations
- Speech models
  - [ ] Speech-to-Text (STT)
  - [ ] Text-to-Speech (TTS)
- Video models
  - [ ] Luma AI Text-to-Video
